### PR TITLE
Sign convention

### PR DESCRIPTION
**Pull request by jl-wynen**
Change the sign of the hopping matrix and chemical potential in the exponential discretization to match the diagonal. As discussed in #17

### CODE REVIEW

**Comment by evanberkowitz** [comment]
I agree that this change harmonizes the exponential and diagonal sign conventions, both for the hopping matrix and for the chemical potential.

Do these changes change anything in the "other" algorithms?  I'm thinking specifically Variant 2, where Q=(two Ms) is required?

**Comment by evanberkowitz** [comment]
What I mean is: I see the signs are changed in the docs, but there aren't any signs in other _code_ that needs to be changed?

**Comment by evanberkowitz** [comment]
I found these also:

```
hubbardFermiMatrixExp.hpp:256:        /// exp(-kappaTilde+muTilde) for particles.
hubbardFermiMatrixExp.hpp:258:        /// exp(kappaTilde-muTilde) for particles.
hubbardFermiMatrixExp.hpp:260:        /// exp(-sigmaKappa*kappaTilde-muTilde) for holes.
hubbardFermiMatrixExp.hpp:262:        /// exp(sigmaKappa*kappaTilde+muTilde) for holes.
hubbardFermiMatrixExp.cpp:593:        // Use version -i Phi - N_t log(det(e^{sigmaKappa*kappa+mu})) + log(det(1+hat{A}^{-1})).
```

I don't think the changes in this PR addressed these signs.  I know they're all in documentation, but still, better to get them right.  Do they need to be flipped?

**Comment by jl-wynen** [comment]
Good catch! Changed the signs in those places as well as the corresponding place in the TeX file.

**Comment by evanberkowitz** [comment]
Found a few more (I think):

```
cpp/hubbardFermiMatrixExp.hpp:69:         * \returns \f$\exp(-\tilde{\kappa} + \tilde{\mu})\f$ for particles
cpp/hubbardFermiMatrixExp.hpp:70:         *          and \f$\exp(-\sigma_{\tilde{\kappa}}\tilde{\kappa} - \tilde{\mu})\f$ for holes.
```

Do those need changing?

**Comment by evanberkowitz** [comment]
Those are all the signs I found by grepping around.  If you also don't see others then let's declare all the signs fixed and close this nightmare chapter forever.

**Comment by evanberkowitz** [comment]
Woohoo!

**Pull request merged**
